-- =============================================
-- ISUFI Hub - Database Schema per Supabase
-- =============================================

-- 1. Tabella PROFILI (Estende gli utenti autenticati)
CREATE TABLE profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL PRIMARY KEY,
  nickname TEXT UNIQUE NOT NULL,
  course TEXT,
  year INTEGER,
  avatar_url TEXT,
  bio TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- 2. Tabella APPUNTI (I documenti caricati)
CREATE TABLE notes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  subject TEXT NOT NULL,
  area TEXT NOT NULL,
  year INTEGER NOT NULL,
  type TEXT NOT NULL,
  uploader_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  uploader_name TEXT NOT NULL,
  file_url TEXT NOT NULL,
  description TEXT,
  tags TEXT[] DEFAULT '{}',
  downloads INTEGER DEFAULT 0,
  rating NUMERIC(3,1) DEFAULT 0.0,
  rating_count INTEGER DEFAULT 0,
  views INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- 3. Tabella PREFERITI (Per salvare i documenti)
CREATE TABLE saved_notes (
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  note_id BIGINT REFERENCES notes(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
  PRIMARY KEY (user_id, note_id)
);

-- 4. Tabella VALUTAZIONI (Sistema di rating)
CREATE TABLE ratings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  note_id BIGINT REFERENCES notes(id) ON DELETE CASCADE,
  score INTEGER NOT NULL CHECK (score >= 1 AND score <= 5),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
  UNIQUE(user_id, note_id)
);

-- 5. Tabella SEGNALAZIONI (Per moderazione contenuti)
CREATE TABLE reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reporter_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  note_id BIGINT REFERENCES notes(id) ON DELETE CASCADE,
  reason TEXT NOT NULL,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'reviewed', 'resolved')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- =============================================
-- ROW LEVEL SECURITY (RLS)
-- =============================================

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE saved_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE ratings ENABLE ROW LEVEL SECURITY;
ALTER TABLE reports ENABLE ROW LEVEL SECURITY;

-- Profili: tutti possono leggere, solo il proprietario può modificare
CREATE POLICY "Public profiles are viewable by everyone." ON profiles FOR SELECT USING (true);
CREATE POLICY "Users can update own profile." ON profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Users can insert own profile." ON profiles FOR INSERT WITH CHECK (auth.uid() = id);

-- Note: tutti possono leggere, solo l'uploader può inserire/modificare/eliminare
CREATE POLICY "Notes are viewable by everyone." ON notes FOR SELECT USING (true);
CREATE POLICY "Users can insert their own notes." ON notes FOR INSERT WITH CHECK (auth.uid() = uploader_id);
CREATE POLICY "Users can update their own notes." ON notes FOR UPDATE USING (auth.uid() = uploader_id);
CREATE POLICY "Users can delete their own notes." ON notes FOR DELETE USING (auth.uid() = uploader_id);

-- Preferiti: solo l'utente proprietario può gestire i propri
CREATE POLICY "Users can manage their own saved notes." ON saved_notes FOR ALL USING (auth.uid() = user_id);

-- Valutazioni: tutti possono leggere, utenti loggati possono inserire/modificare le proprie
CREATE POLICY "Ratings are viewable by everyone." ON ratings FOR SELECT USING (true);
CREATE POLICY "Users can insert their own ratings." ON ratings FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own ratings." ON ratings FOR UPDATE USING (auth.uid() = user_id);

-- Segnalazioni: solo l'utente può creare le proprie
CREATE POLICY "Users can insert reports." ON reports FOR INSERT WITH CHECK (auth.uid() = reporter_id);
CREATE POLICY "Users can view their own reports." ON reports FOR SELECT USING (auth.uid() = reporter_id);

-- =============================================
-- FUNZIONI E TRIGGER
-- =============================================

-- Funzione per aggiornare il rating medio di una nota quando viene inserita/aggiornata una valutazione
CREATE OR REPLACE FUNCTION update_note_rating()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE notes SET
    rating = (SELECT COALESCE(AVG(score), 0) FROM ratings WHERE note_id = NEW.note_id),
    rating_count = (SELECT COUNT(*) FROM ratings WHERE note_id = NEW.note_id)
  WHERE id = NEW.note_id;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_rating_change
  AFTER INSERT OR UPDATE ON ratings
  FOR EACH ROW EXECUTE FUNCTION update_note_rating();

-- Funzione per aggiornare il timestamp updated_at
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_profiles_timestamp
  BEFORE UPDATE ON profiles
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER update_notes_timestamp
  BEFORE UPDATE ON notes
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- =============================================
-- INDICI PER PERFORMANCE
-- =============================================

CREATE INDEX idx_notes_area ON notes(area);
CREATE INDEX idx_notes_subject ON notes(subject);
CREATE INDEX idx_notes_uploader_id ON notes(uploader_id);
CREATE INDEX idx_notes_created_at ON notes(created_at DESC);
CREATE INDEX idx_notes_downloads ON notes(downloads DESC);
CREATE INDEX idx_notes_rating ON notes(rating DESC);
CREATE INDEX idx_saved_notes_user_id ON saved_notes(user_id);
CREATE INDEX idx_ratings_note_id ON ratings(note_id);
CREATE INDEX idx_ratings_user_id ON ratings(user_id);

-- 6. Tabella NOTIFICHE (Per avvisi su commenti o segnalazioni)
CREATE TABLE notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  note_id BIGINT REFERENCES notes(id) ON DELETE CASCADE,
  actor_name TEXT,
  message TEXT,
  type TEXT,
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own notifications." ON notifications FOR ALL USING (auth.uid() = user_id);
CREATE INDEX idx_notifications_user_id ON notifications(user_id);

